FROM busybox

CMD echo "Hello world! This is my first Docker image."

# V Old code V
#FROM openjdk:8-jre-slim as production

#EXPOSE 8080

#RUN mkdir /app

#COPY --from=build /app/target/spring-petclinic-*.jar /spring-petclinic.jar

#CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/spring-petclinic.jar"]
